apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-controller
  labels:
    workqueue: active
    reporter: active
spec:
  containers:
  - name: funkytown-controller
    image: funkytownacr.azurecr.io/controller:{{ .Values.imageTag }}
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 250m
        memory: 64Mi
      limits:
        cpu: 500m
        memory: 128Mi
    ports:
      - containerPort: 6379
      - containerPort: 3000