apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-worker-job
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
      containers:
      - name: funkytown-worker-job
        image: funkytownacr.azurecr.io/worker:{{ .Values.imageTag }}
        imagePullPolicy: IfNotPresent
        env:
      - name: REDIS_HOST
        valueFrom:
            configMapKeyRef:
                name: {{ .Release.Name }}-config
                key: workqueueService
          - name: REDIS_PORT
            value: "6379"
        volumeMounts:
          - mountPath: /dev/shm
            name: dshm
        resources:
          requests:
            memory: 256Mi
            cpu: 500m
          limits:
            memory: 4096Mi
            cpu: 2000m
      restartPolicy: Never
      hostIPC: true
