apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-worker
spec:
  volumes:
  - name: dshm
    emptyDir:
      medium: Memory
  containers:
  - name: funkytown-worker
    image: worker
    imagePullPolicy: Never
    env:
      - name: REDIS_HOST
        valueFrom:
            configMapKeyRef:
                name: {{ .Release.Name }}-config
                key: workqueueService
      - name: REDIS_PORT
        value: "40379"
    volumeMounts:
      - mountPath: /dev/shm
        name: dshm
    resources:
      limits:
        memory: "256Mi"
        cpu: "1000m"
  restartPolicy: Never
  hostIPC: true
