apiVersion: v1
kind: Pod
metadata:
  name: funkytown-controller
  labels:
    workqueue: active
    reporter: active
spec:
  containers:
  - name: funkytown-controller
    image: funkytownacr.azurecr.io/controller:649be1375f0b4df04532d1a2312b8f3cae1772a5
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 250m
        memory: 64Mi
      limits:
        cpu: 500m
        memory: 128Mi
    ports:
      - containerPort: 6379
      - containerPort: 3000
