apiVersion: v1
kind: Pod
metadata:
  name: funkytown-controller
  labels:
    workqueue: active
    reporter: active
spec:
  containers:
  - name: funkytown-controller
    image: funkytownacr.azurecr.io/controller:5bdb29aa260fa262b19e12ba2d6e1cd823c800a7
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 250m
        memory: 64Mi
      limits:
        cpu: 500m
        memory: 128Mi
    ports:
      - containerPort: 6379
      - containerPort: 3000
