apiVersion: v1
kind: Pod
metadata:
  name: funkytown-worker-debug
spec:
  volumes:
  - name: dshm
    emptyDir:
      medium: Memory
  containers:
  - name: funkytown-worker
    command: [ "/bin/sh" ]
    args: ["-c", "while true; do tail -f /dev/null; sleep 60000;done"]
    image: funkytownacr.azurecr.io/controller:5bdb29aa260fa262b19e12ba2d6e1cd823c800a7
    imagePullPolicy: IfNotPresent
    env:
      - name: REDIS_HOST
        value: funkytown-workqueue-service
      - name: REDIS_PORT
        value: "6379"
    volumeMounts:
      - mountPath: /dev/shm
        name: dshm
    resources:
      requests:
        memory: 256Mi
        cpu: 500m
      limits:
        memory: 4096Mi
        cpu: 2000m
  restartPolicy: Never
  hostIPC: true
