apiVersion: v1
kind: Pod
metadata:
  name: funkytown-worker-debug
spec:
  volumes:
  - name: dshm
    emptyDir:
      medium: Memory
  containers:
  - name: funkytown-worker
    command: [ "/bin/sh" ]
    args: ["-c", "while true; do tail -f /dev/null; sleep 60000;done"]
    image: worker
    imagePullPolicy: Never
    env:
      - name: REDIS_HOST
        value: funkytown-workqueue-service
      - name: REDIS_PORT
        value: "40379"
    volumeMounts:
      - mountPath: /dev/shm
        name: dshm
    resources:
      limits:
        memory: "256Mi"
        cpu: "1000m"
  restartPolicy: Never
  hostIPC: true
